# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('I', 'Init'), ('A', 'Active'), ('S', 'Stopped'), ('D', 'Deleted')], max_length=1)),
            ],
        ),
    ]
