# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 2, 9, 53, 26, 947000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
