# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_template_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='cluster',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
